### Test 1
GET https://google.com
# @expect-status 200

### Test Post request
POST https://dummyjson.com/posts/add
Content-Type: application/json

{
  "title": "I am in love with someone.", 
  "userId": 5, 
  "body": "Your post content here"
}

# @expect-status 201
# @expect-response {
# "userId":5, 
# "id":252,
# "title":"I am in love with someone.",
# "body":"Your post content here"
# }
