[TEST1]
GET https://google.com
200



[TEST2]
GET https://google.com
200

[TEST3]
GET https://google.com
200

[TEST4]
GET https://google.com
300

[Test Post Request]
POST https://dummyjson.com/posts/add
DATA {"title": "I am in love with someone.", "userId": 5, "body": "Your post content here"}
201
